= MHS Adaptor Integration Tests

This package contains a the integration tests intended to pre-assure the Message Handling Service and all the
associated services/interfaces used in the Spine messaging. 

== Pre-requisites for Integration Tests

You must first have establish connectivity to an NHS Digital integration testing environment link:../../setup-opentest.md[such as OpenTest].

== Running the Integration Tests from PyCharm locally

The term "integration" test here refers to end-to-end testing of the MHS Adaptor through integrating with an NHS Digital
test environment such as OpenTest. These integration tests cover positive testing scenarios
only.

`pipenv run inttests` will run all integration tests.

When running the tests locally, you will need to set the MHS_ADDRESS, ASID, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, MHS_DB_ENDPOINT_URL in the 'Environment variables' section of
 the Run/Debug Configurations.
- The INTEGRATION_TEST_ASID is a 12 digit number needed to access Opentest, supplied by NHS Digital
 - eg INTEGRATION_TEST_ASID=123456789012
- The MHS_ADDRESS is the URL of the MHS instance being used for testing
 - eg MHS_ADDRESS=http://localhost
- The AWS_ACCESS_KEY_ID can be 'test' locally.
- The AWS_SECRET_ACCESS_KEY can be 'test' locally.
- MHS_DB_ENDPOINT_URL can be http://localhost:8000 locally.

You will need to complete the setup steps for all the associated services in test prior to running this test suite

== Running the Integration Tests from the Command Line locally

The environment variable described above will need to be present in the environment, using a bash script:

[source,bash]
----
export MHS_ADDRESS="http://localhost"
export SCR_ADDRESS="http://localhost:9000/"
export INTEGRATION_TEST_ASID="Your NHS Digital assigned ASID here"
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export MHS_DB_ENDPOINT_URL="http://localhost:8000"

----

The URL's above should be those defined in your `docker-compose.yml` file. The script can be executed throught the `source` command.

Run `pipenv run inttests` from this directory.

Note:
If you experience an error `No module name xmlrunner`, you will need to run the command `pip install unittest-xml-reporting`

== Running the Component Tests

Component tests here are defined as integration tests which test the MHS Alpha, integrating with a mocked spine instance
which has been created to enable local negative testing scenarios which are not possible using OpenTest.

`pipenv run componenttests` will run all component tests.

To setup the test environment locally, run the following commands from the root directory:

[source,bash]
----
./setup_component_test_env.sh
source ./component-test-source.sh
docker-compose -f docker-compose.yml -f docker-compose.component.override.yml -p custom_network up --build
----

== Starting the services as docker containers

=== Prerequisites

The following is required:

 Docker
 OpenTest VPN Connection

. Create a script in the project root directory to start the containers, call it `export-env-vars.sh` and make it executable.

. Add the following content and your OpenTest details into the file

.export-env-vars.sh
[source,bash]
----
echo "Exporting environment variables"

export BUILD_TAG="latest"
export MHS_OUTBOUND_VALIDATE_CERTIFICATE="False"

# Your OpenTest Party key here
export MHS_SECRET_PARTY_KEY=""

# Your OpenTest endpoint certificate here
export MHS_SECRET_CLIENT_CERT=""

# Your OpenTest endpoint private key here
export MHS_SECRET_CLIENT_KEY=""

# OpenTest Endpoint issuing subCA certificate and Root CA certificate here
export MHS_SECRET_CA_CERTS=""
----
[start=3]
. Confirm you are connected to the OpenTest VPN and start all the containers by executing the shell script you created above.

`./export-env-vars.sh`

[start=4]
. To start the containers run the command:

`docker-compose -f docker-compose.yml -f docker-compose.lb.override.yml -f docker-compose.release.image.override.yml up -d --build`

[start=5]

. To scale up the inbound and outbound containers run the command:

`docker-compose -f docker-compose.yml -f docker-compose.lb.override.yml scale inbound=3 outbound=3`

==== Technical notes about the scalable cluster

By default docker-compose starts 1 instance per service.
To be able scale up, a load balance has to be added to the cluster,
target service has to have internal port to ephemeral binding
and and environment variable has to be set for HTTPS comm.

The `docker-compose.lb.override.yml` contains additional definitions for 2 load balancers - inbound + outbound services.

== Sending requests using Visual Studio Code
This section explains how to send requests to OpenTest which is the NHS Spine Test System.
The requests are sent via the docker containers which can be setup following the previous section: <<Starting the services as docker containers>>

. Open Visual Studio Code
. Check out the integration-adapter project on the develop branch from github: https://github.com/nhsconnect/integration-adaptors
. In the project root create the directory `.vscode` if it doesn't exist already
. In the .vscode folder create a file called `settings.json`
. Add the information below to the `settings.json` file
[source,json]
----
{
    "python.pythonPath": "/usr/local/bin/python3",
    "workbench.settings.editor": "json",
    "workbench.settings.useSplitJSON": true,
    "rest-client.environmentVariables": {
        "$shared": {},
        "$sample_mhs_environment": {
            "BASE_URL": "http://localhost",
                        "INBOUND-PORT": "8082",
                        "OUTBOUND-PORT": "80",
                        "ROUTE-LOOKUP-PORT": "8088",
                        "FAKE-SPINE-PORT": "8091",
                        "ASID": "9XXXXXXXXXXX",
                        "PARTY-KEY": "A9XXXX-XXXXXXX"
        }
    }
}
----
. Navigate the code directories to the requests: `/http-client/mhs/outbound`
. Navigate to the folder of the message pattern type you wish to run a request for and open a request .http file
. In the bottom right corner of Visual Studio Code click `No Environment` and select `$sample_mhs_environment`
. Change the data `@PATIENT_NHS_NUMBER` to be a number which is valid in OpenTest. A correct number can be found in the
correct integration test for the same message pattern type.

The integration tests can be found in `/integration-tests/integration_tests/integration_tests/end_to_end_tests`
[start=10]
. Click the `Send Request` link which can be found inside the .http file request

== Running integration tests against fake components

Run `fake_spine` and `fake_spineroutelookup` as if running component tests
Run `inbound` and `outbound` with the `all_component_test_env.yaml` configuration (same as of running component tests)
Run the integration tests using the `all_component_test_env.yaml` instead of the normal integration test configuration.

== Fake Spine request / response delays

There are two environment variables that can control how quickly Fake Spine responds:

* `FAKE_SPINE_OUTBOUND_DELAY_MS` (default: 0) controls the minimum time the service will take to handle each outbound request
* `FAKE_SPINE_INBOUND_DELAY_MS` (default: 0) controls how much time after the outbound request completes that the service will send the asynchronous inbound response