
// 400: Invalid request. Validation errors: {'payload': ['Field may not be null.']}

# @name Return_bad_request_when_client_sends_invalid_message
POST http://localhost HTTP/1.1
interaction-id: QUPC_IN160101UK05
message-id: 
sync-async: false
from-asid: {{ASID}}
Content-Type: application/json
ods-code: YES
