
// 400: Invalid request. Validation errors: {'payload': ['Not a valid string.']}

# @name Return_bad_request_when_client_sends_invalid_message
POST http://localhost HTTP/1.1
Interaction-Id: QUPC_IN160101UK05
message-id: ''
sync-async: false
from-asid: {{ASID}}
Content-Type: application/json
ods-code: YES

{
    "payload": "<QUPC_IN160101UK05 xmlns=\"urn:hl7-org:v3\">\r\n<blah=\"123\"/>\r\n</QUPC_IN160101UK05>\r\n"
}