apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-mesh
  name: fake-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-mesh
  template:
    metadata:
      labels:
        app: fake-mesh
    spec:
      containers:
      - image: nhsdev/fake-mesh:0.2.0
        name: fake-mesh
        ports:
        - containerPort: 8829
