----=_MIME-Boundary
Content-Id: <ebXMLHeader@spine.nhs.uk>
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit

{{ebxml}}
----=_MIME-Boundary
Content-Id: <C614484E-4B10-499A-9ACD-5D645CFACF61@spine.nhs.uk>
Content-Type: application/xml
Content-Transfer-Encoding: 8bit

<hl7:MCCI_IN010000UK13 xmlns:hl7="urn:hl7-org:v3"/>
----=_MIME-Boundary
Content-Id: <8F1D7DE1-02AB-48D7-A797-A947B09F347F@spine.nhs.uk>
Content-Type: text/plain
Content-Transfer-Encoding: 8bit

Some payload
----=_MIME-Boundary--
