
# @name Return_a_bad_request_to_the_client_when_the_client_provides_a_bad_request
POST {{LOCAL_SCR_URL}} HTTP/1.1
Interaction-name: SCR_GP_SUMMARY_UPLOAD
Message-Id: AD7D39A8-1B6C-4520-8367-6B7BEBD7B842
Correlation-Id: 2

{
  "Id": "{{GUID-idRoot}}",
  "creationTime": "{{SHORT-TIMESTAMP}}",
  "versionCode": "V3NPfIT4.2.00",
  "communicationFunctionRcv": {
    "device": {
      "id": {
        "extension": "227319907548"
      }
    }
  },
  "communicationFunctionSnd": {
    "device": {
      "id": {
        "extension": "{{ASID}}"
      }
    }
  },
  "controlActEvent": {
    "author1": {
      "agentSystemSDS": {
        "id": {
          "extension": "{{ASID}}"
        }
      }
    },
    "author": {
      "AgentPersonSDS": {
        "id": {
          "extension": "055888118514"
        },
        "agentPersonSDS": {
          "id": {
            "extension": "979603625513"
          }
        },
        "part": {
          "partSDSRole": {
            "id": {
              "extension": "R0260"
            }
          }
        }
      }
    },
    "subject": {
      "GPSummary": {
        "id": {
          "root": "{{GUID-idRoot}}"
        },
        "effectiveTime": "{{SHORT-TIMESTAMP}}",
        "author": {
          "time": "{{SHORT-TIMESTAMP}}",
          "AgentPersonSDS": {
            "id": {
              "extension": "055888118514"
            },
            "agentPersonSDS": {
              "id": {
                "extension": "979603625513"
              },
              "name": "<family>NICA_Test_Automation_Healthchecks</family>"
            }
          }
        },
        "excerptForm": {
          "CareDocs": {
            "presentationText": {
              "value": "<h1>header</h1>",
              "id": {
                "root": "EA3BCDEB-A439-4984-A519-2EE25EB3F24C"
              },
              "effectiveTime": {
                "value": "{{SHORT-TIMESTAMP}}"
              }
            }
          }
        },
        "recordTarget": {
          "patient": {
            "id": {
              "extension": "9446245796"
            }
          }
        }
      }
    }
  }
}
