
# @name Async_Express
POST https://192.168.128.11/reliablemessaging/queryrequest HTTP/1.1
charset: UTF-8
SOAPAction: urn:nhs:names:services:psisquery/QUPC_IN160101UK05
content-type: multipart/related; boundary="--=_MIME-Boundary"; type=text/xml; start=ebXMLHeader@spine.nhs.uk


----=_MIME-Boundary
Content-Id: <ebXMLHeader@spine.nhs.uk>
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit

<?xml version="1.0" encoding="UTF-8"?>
<SOAP:Envelope xmlns:xsi="http://www.w3c.org/2001/XML-Schema-Instance" xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/" xmlns:eb="http://www.oasis-open.org/committees/ebxml-msg/schema/msg-header-2_0.xsd" xmlns:hl7ebxml="urn:hl7-org:transport/ebXML/DSTUv1.0" xmlns:xlink="http://www.w3.org/1999/xlink">
<SOAP:Header>
	<eb:MessageHeader SOAP:mustUnderstand="1" eb:version="2.0">
		<eb:From>
			<eb:PartyId eb:type="urn:nhs:names:partyType:ocs+serviceInstance">A91565-9198975</eb:PartyId>
		</eb:From>
		<eb:To>
			<eb:PartyId eb:type="urn:nhs:names:partyType:ocs+serviceInstance">YES-0000806</eb:PartyId>
		</eb:To>
		<eb:CPAId>S20003A000304</eb:CPAId>
		<eb:ConversationId>EAB1E521-85EF-45C3-8465-8E93D622A31E</eb:ConversationId>
		<eb:Service>urn:nhs:names:services:psisquery</eb:Service>
		<eb:Action>QUPC_IN160101UK05</eb:Action>
		<eb:MessageData>
			<eb:MessageId>1286F067-53C2-4222-8C8A-B14FF872D79A</eb:MessageId>
			<eb:Timestamp>2020-02-25T14:39:54Z</eb:Timestamp>
		</eb:MessageData>
    </eb:MessageHeader>
    <eb:SyncReply SOAP:mustUnderstand="1" eb:version="2.0" SOAP:actor="http://schemas.xmlsoap.org/soap/actor/next"/>
</SOAP:Header>
<SOAP:Body>
	<eb:Manifest SOAP:mustUnderstand="1" eb:version="2.0">
		<eb:Reference xlink:href="cid:1286F067-53C2-4222-8C8A-B14FF872D79A@spine.nhs.uk">
			<eb:Schema eb:location="http://www.nhsia.nhs.uk/schemas/HL7-Message.xsd" eb:version="1.0"/>
			<eb:Description xml:lang="en">HL7 payload</eb:Description>
			<hl7ebxml:Payload style="HL7" encoding="XML" version="3.0"/>
		</eb:Reference>
	</eb:Manifest>
</SOAP:Body>
</SOAP:Envelope>

----=_MIME-Boundary
Content-Id: <1286F067-53C2-4222-8C8A-B14FF872D79A@spine.nhs.uk>
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit

<QUPC_IN160101UK05 xmlns="urn:hl7-org:v3">
            <id root="AF347245-C97B-483D-8DB1-5C57A7256885" />
            <creationTime value="20190927152034"/>
            <versionCode code="3NPfIT7.2.00" />
            <interactionId root="2.16.840.1.113883.2.1.3.2.4.12" extension="QUPC_IN160101UK05" />
            <processingCode code="P" />
            <processingModeCode code="T" />
            <acceptAckCode code="NE" />
            <communicationFunctionRcv typeCode="RCV">
                <device classCode="DEV" determinerCode="INSTANCE">
                    <id extension="YES-0000806" root="1.2.826.0.1285.0.2.0.107" />
                </device>
            </communicationFunctionRcv>
            <communicationFunctionSnd typeCode="SND">
                <device classCode="DEV" determinerCode="INSTANCE">
                    <id extension="{{ASID}}" root="1.2.826.0.1285.0.2.0.107" />
                </device>
            </communicationFunctionSnd>
            <ControlActEvent classCode="CACT" moodCode="EVN">
                <author1 typeCode="AUT">
                    <AgentSystemSDS classCode="AGNT">
                        <agentSystemSDS classCode="DEV" determinerCode="INSTANCE">
                            <id extension="{{ASID}}" root="1.2.826.0.1285.0.2.0.107" />
                        </agentSystemSDS>
                    </AgentSystemSDS>
                </author1>
                <query>
                    <dissentOverride>
                        <semanticsText>DissentOverride</semanticsText>
                        <value code="0" codeSystem="2.16.840.1.113883.2.1.3.2.4.17.60" displayName="Demonstration">
                            <originalText>Demonstration</originalText>
                        </value>
                    </dissentOverride>
                    <filterParameters>
                        <date>
                            <semanticsText>Date</semanticsText>
                            <value>
                                <low value="20100908161126"/>
                                <high value="20190927152034"/>
                            </value>
                        </date>
                    </filterParameters>
                    <nHSNumber>
                        <semanticsText>NHSNumber</semanticsText>
                        <value root="2.16.840.1.113883.2.1.4.1" extension="9689177923" />
                    </nHSNumber>
                </query>
            </ControlActEvent>
</QUPC_IN160101UK05>

----=_MIME-Boundary--
