FROM python:3.7-slim as base
# TODO: nhais doesn't use the tornado client so we shouldn't need curl but I can't exclude it
#RUN apt-get update && \
#    apt-get install build-essential libcurl4-openssl-dev libssl-dev -y
RUN apt-get update && apt-get install build-essential -y
RUN pip install pipenv
RUN mkdir -p /usr/src/app/nhais
# TODO: should just be . after NIAD-193
# COPY . /usr/src/app/nhais
COPY ./nhais/ /usr/src/app/nhais
# TODO: Remove common after NIAD-193
RUN mkdir -p /usr/src/app/common
COPY ./common/ /usr/src/app/common
WORKDIR /usr/src/app/nhais
RUN pipenv install -d
RUN printf "#!/bin/sh\npipenv run unittests && pipenv run componenttests && pipenv run inttests" > test.sh
RUN chmod +x test.sh
ENTRYPOINT ["/usr/src/app/nhais/test.sh"]
